### ISSUE TITLE
Original URI does not have a trailing slash

### ISSUE THREAD

**Issue by machawk1** [machawk1/cdxjGenerator#11]
Per @ibnesayeed in #4 

The CDXJ lines contain JSON attributes like ` "original_uri": "http://nfuicnh7admnrh.ao",`

Is a trailing slash required for the value?

**Comment by ibnesayeed** [comment]
No, the trailing slash is not *required*, but is the agreed on style of representing a canonical root page HTTP URI.

**Comment by machawk1** [comment]
@ibnesayeed I believe you but can you provide a reference to where it is agreed on for my future reference? I do not usually write a slash after a URI-R when browsing the live web. Perhaps some folks do.

**Comment by ibnesayeed** [comment]
> I do not usually write a slash after a URI-R when browsing the live web.

In your web browser's address bar type `example.com` and hit `ENTER`. Then copy the loaded URL from the address bar and paste it somewhere. At least, in Chrome, you will find that it automatically added scheme and trailing slash.

**Comment by machawk1** [comment]
Ok, I am convinced.

This value might be provided, so can also include a path. What do you think is an elegant solution for ensuring that if only the hostname is used for the URI-R that it ends in a "/"?

The solutions I initially think of would convolute what is current straight-forward logic for an aspect of fabricated data that is _optional_.

**Comment by ibnesayeed** [comment]
> This value might be provided, so can also include a path. What do you think is an elegant solution for ensuring that if only the hostname is used for the URI-R that it ends in a "/"?
> 
> The solutions I initially think of would convolute what is current straight-forward logic for an aspect of fabricated data that is _optional_.

```
fake.uri()
```

**Comment by machawk1** [comment]
Fixed in 82fb0bc8b421c6b2e9adafada5c598a43d329853.
